services:
  # rabbitmq
  rabbitmq:
    image: rabbitmq:4.2.3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "is_running"]
      interval: 5s
      timeout: 5s
      retries: 20

  # python code reading file system
  scanner:
    image: fs2mq:0.1.0
    platform: linux/amd64
    container_name: fs2mq
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: 
      - .env
    volumes:
      - ./data:/data:ro
    command:
      - .venv/bin/python
      - -m
      - fs2mq.scanner
      - --root
      - /data
      - --log-every
      - "1000"


volumes:
  rabbitmq_data:
